framework: mocha
preRun:
     command:
        - npm install
        - npm run pretest
preMerge:
  pattern:
    - "./test/test.ts"
postMerge:
  pattern:
    - "./test/test.ts"
postRun:
     command:
        - node --version
configFile: "mocharc.yml"
version: 1.0
